collection_name: agent
embedding_function: DashScopeEmbedding()
persist_directory: chroma_db
k: 3
data_path: data
md5_hex_store: md5.txt
allow_knowledge_file_type: ["txt","pdf"]
chunk_size: 200
chunk_overlap: 20
separator: ["\n\n","\n"," ",",",".","，","。","?","？"]

